name: hp_demo1
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # 图标
  # cupertino_icons: ^0.1.2
  # 加载效果
  flutter_spinkit: ^3.1.0
  # 闪屏效果 已源码实现
  # splashscreen: ^1.2.0
  common_utils: ^1.1.0
  # 图片介绍页
  intro_views_flutter: ^2.6.0
  # 主页图片滚动介绍页
  flutter_swiper: ^1.1.6
  # http client
  dio: ^2.1.13
  # 缓存管理
  flutter_cache_manager: "^1.1.0"
  # A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: ^1.1.1
  # pull up load and pull down refresh
  pull_to_refresh: ^1.5.4
  # 音频播放
  audioplayers: ^0.13.1
  # 屏幕适配
  flutter_screenutil: ^0.5.3
  # 瀑布流
  flutter_staggered_grid_view: ^0.3.0
  # 下拉菜单
  dropdown_menu: ^1.1.1
  # 打开外部app
  url_launcher: ^5.1.2
  # 顶吸效果 可代替SliverPersistentHeader 暂未使用
  sticky_headers: "^0.1.8"
  # webview
  flutter_webview_plugin: ^0.3.7
  # 第三方drawer
  drawerbehavior: ^0.0.8
  # 颜色选择器
  # flutter_colorpicker: ^0.2.1
  # 键值对持久化
  shared_preferences: ^0.5.3+5
  # 微信调用
  fluwx: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/chinesexingshu.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
